name: 'install Hurl'
description: 'Installs Hurl'
  

runs:
  using: "composite"
  steps:
    - run: |
       curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/6.1.0/hurl_6.1.0_amd64.deb
       sudo dpkg -i hurl_6.1.0_amd64.deb
      shell: bash
    - run: hurl --version
      shell: bash
