name: 'install just'
description: 'Installs just'
  

runs:
  using: "composite"
  steps:
    - run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        echo "HOMEBREW_PREFIX=$(/home/linuxbrew/.linuxbrew/bin/brew --prefix)" >> $GITHUB_ENV
        echo "$(/home/linuxbrew/.linuxbrew/bin/brew --prefix)/bin" >> $GITHUB_PATH
      shell: bash  
    - name: install just
      run: /home/linuxbrew/.linuxbrew/bin/brew install just
      shell: bash
    
    - run: just --version
      shell: bash
